import os
import google.generativeai as genai
from dotenv import load_dotenv
import json

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")
if API_KEY:
    genai.configure(api_key=API_KEY)

def get_gemini_critique(plan_json: list):
    """
    Critique Agent: Acts as a Senior Medical Administrator.
    """
    if not API_KEY:
        return "Gemini API Key not found. Cannot generate critique."

    model = genai.GenerativeModel('gemini-2.0-flash-lite-preview-02-05')
    
    prompt = f"""
    Role: You are a Senior Medical Administrator for Mumbai's Healthcare System.
    Task: Review the following patient transfer plan generated by an algorithm.
    
    Allocation Plan:
    {json.dumps(plan_json, indent=2)}
    
    Context:
    - Mumbai has heavy traffic; long-distance transfers are risky.
    - Overcrowding leads to cross-infection.
    - Staff fatigue is a concern.
    
    Output:
    Provide a structured critique in JSON format with the following keys:
    - "risk_score": (1-10, where 10 is high risk)
    - "concerns": [List of specific issues]
    - "recommendations": [Strategic improvements]
    - "sanity_check": "PASS" or "FAIL"
    
    Return ONLY the JSON string.
    """
    
    try:
        response = model.generate_content(prompt)
        # Clean up code blocks if present
        text = response.text.replace("```json", "").replace("```", "").strip()
        return text
    except Exception as e:
        return f"Error generating critique: {str(e)}"

def get_patient_advisory(symptoms: str, location: dict):
    """
    Advisory Agent: Acts as an Empathetic Medical Assistant.
    """
    if not API_KEY:
        return "Gemini API Key not found. Cannot generate advisory."

    model = genai.GenerativeModel('gemini-2.0-flash-lite-preview-02-05')
    
    prompt = f"""
    Role: You are an Empathetic Medical Assistant.
    Patient Symptoms: "{symptoms}"
    Patient Location: {location}
    
    Task: Triage the patient.
    
    Output:
    Return a JSON object with:
    - "recommendation": "Go to Hospital" or "Home Care" or "Consult Doctor"
    - "urgency": "High", "Medium", "Low"
    - "specialist": "General Physician", "Pulmonologist", "Cardiologist", etc.
    - "reason": A brief, empathetic explanation (max 2 sentences).
    - "nearest_hospital_type": Suggest the type of facility (e.g., "Tertiary Care", "Local Clinic").
    
    Return ONLY the JSON string.
    """
    
    try:
        response = model.generate_content(prompt)
        text = response.text.replace("```json", "").replace("```", "").strip()
        return json.loads(text) # Return parsed JSON for the frontend to handle
    except Exception as e:
        return {
            "recommendation": "Error",
            "reason": "Could not generate advice at this time. Please visit a doctor.",
            "urgency": "High"
        }
